export enum Provider { OPENROUTER = 'openrouter', PERPLEXITY = 'perplexity' }
export enum SonarModel { SONAR = 'sonar', SONAR_PRO = 'sonar-pro', SONAR_REASONING = 'sonar-reasoning', SONAR_REASONING_PRO = 'sonar-reasoning-pro', SONAR_DEEP_RESEARCH = 'sonar-deep-research' }
export enum GeneralModel { GPT4O_MINI = 'openai/gpt-4o-mini', GPT4O = 'openai/gpt-4o', CLAUDE_HAIKU = 'anthropic/claude-haiku-4', CLAUDE_SONNET = 'anthropic/claude-sonnet-4', CLAUDE_OPUS = 'anthropic/claude-opus-4', GEMINI_FLASH = 'google/gemini-2.5-flash', GEMINI_PRO = 'google/gemini-2.5-pro', O1 = 'openai/o1', O3 = 'openai/o3' }
export enum TaskComplexity { TRIVIAL = 'trivial', LOW = 'low', MEDIUM = 'medium', HIGH = 'high', CRITICAL = 'critical' }
export enum TaskType { CLASSIFICATION = 'classification', EXTRACTION = 'extraction', SCORING = 'scoring', CONTENT_GENERATION = 'content_generation', STRATEGIC_REASONING = 'strategic_reasoning', CODE_GENERATION = 'code_generation', COMPETITOR_RESEARCH = 'competitor_research', CITATION_CHECK = 'citation_check', FACT_VERIFICATION = 'fact_verification', MARKET_RESEARCH = 'market_research', LINK_PROSPECTING = 'link_prospecting', VISUAL_QA = 'visual_qa', SCREENSHOT_ANALYSIS = 'screenshot_analysis', LAYOUT_VALIDATION = 'layout_validation' }
export interface TaskDescriptor { type: TaskType; complexity: TaskComplexity; clientId?: string; description?: string; expectedOutputTokens?: number; requiresSearch?: boolean; images?: string[] }
export interface RouterConfig { perplexityApiKey: string; openrouterApiKey: string; appName?: string }
export interface LLMResponse { content: string; model: string; provider: Provider; inputTokens: number; outputTokens: number; totalTokens: number; cost: number; latencyMs: number; cached: boolean; citations?: string[] }
export interface RoutingDecision { taskId: string; clientId: string; taskType: TaskType; complexity: TaskComplexity; provider: Provider; model: string; estimatedCost: number; actualCost?: number; reason: string; timestamp: string }
